version: '3.4'

services:

  db:
    build: db
    image: barakbd/k8s-wordsmith-demo-db
    container_name: wordsmith-db

  api:
    container_name: wordsmith-api
    build: api
    image: barakbd/k8s-wordsmith-demo-api
    deploy:
      replicas: 5

  web:
    container_name: wordsmith-web
    build: 
      context: web
      target: test
      args: 
        UNIT_TEST_EXIT_CODE: 0

    image: barakbd/k8s-wordsmith-demo-web
    environment: 
      - unit_test_exit_code=1
    ports:
      - target: 80
        published: 8080
        mode: host
    # deploy option needed for stack deploy on ubuntu 18.04 - otherwise node is not reachable by localhost
    # https://forums.docker.com/t/different-connectivity-for-run-and-stack/32484
    deploy:
      mode: global 
      
# build - docker-compose build --no-cache --build-arg unit_test_exit_code=1 web
# run - docker stack deploy wordsmith -c docker-compose.yml