version: '3.3'

services:

  db:
    build: db
    image: dockersamples/k8s-wordsmith-db

  words:
    build: words
    image: dockersamples/k8s-wordsmith-api
    deploy:
      replicas: 5

  web:
    build: web
    image: dockersamples/k8s-wordsmith-web
    ports:
      - target: 80
        published: 8080
        mode: host
    # deploy option needed for stack deploy on ubuntu 18.04 - otherwise node is not reachable by localhost
    # https://forums.docker.com/t/different-connectivity-for-run-and-stack/32484
    deploy:
      mode: global 
      